FROM maven:latest as builder

WORKDIR /app

COPY pom.xml .
RUN mvn dependency:go-offline

COPY src ./src
COPY wait-for-mysql.sh ./wait-for-mysql.sh

RUN mkdir /target
RUN mvn clean package
RUN apt-get update
RUN apt-get install -y mysql-client
RUN chmod +x ./wait-for-mysql.sh

EXPOSE 8080

ENTRYPOINT ["/bin/sh", "wait-for-mysql.sh", "mysql", "java", "-jar", "./target/accenture-techhub-0.0.1-SNAPSHOT.war"]
