# Use an official MySQL image as the base image
FROM mysql:8.0

# Set the MySQL root password (change this to a strong, secure password)
ENV MYSQL_ROOT_PASSWORD=rootPWD

# Create a database during container initialization (optional)
ENV MYSQL_DATABASE=accwe-hospital

# Use mysql_native_password as the authentication plugin
#RUN echo "default_authentication_plugin=mysql_native_password" >> /etc/mysql/my.cnf

# Expose the MySQL port
EXPOSE 3306

# Start the MySQL service
CMD ["mysqld"]