# Use an official MySQL image as the base image
FROM mysql:latest

# Set the MySQL root password (change this to a strong, secure password)
ENV MYSQL_ROOT_PASSWORD=rootPWD

# Create a database during container initialization (optional)
ENV MYSQL_DATABASE=accwe-hospital

# Expose the MySQL port
EXPOSE 3306

# Start the MySQL service
CMD ["mysqld"]